### ISSUE TITLE
Website text improvement

### ISSUE THREAD

**Issue by pascalvanhecke** [FundRequest/Marketing-Material#2]
![fundrequest - platform for rewarding open source contributions 2017-01-26 01-12-29](https://cloud.githubusercontent.com/assets/290665/22315036/9087a580-e364-11e6-90df-cd206ae583de.png)

Not clear the sentence continues after "to" in the 4 bullet points.

Suggestion: add ellipsis and change capitalization: "to..."

"... is the increase in"

**Comment by karelstriegel** [comment]
Again thx for the feedback, requested changes have been made.
