### ISSUE TITLE
Website ICO text typo

### ISSUE THREAD

**Issue by pascalvanhecke** [FundRequest/Marketing-Material#3]
![ico - crowdsale fundrequest - rewarding open source contributions 2017-01-26 01-20-23](https://cloud.githubusercontent.com/assets/290665/22315208/b0b058a6-e365-11e6-8583-c288fc6494fc.png)

10 % -> should be 0.1% right?

**Comment by karelstriegel** [comment]
Thank you for taking the time to report the bug. Site + docs have been updated.
